### ISSUE TITLE
New Logo for Flash Bang

### ISSUE THREAD

**Issue by zularizal** [imallett/FlashBang#1]
Hello @imallett ,  I want contribute to FlashBang, so i designed a new logo for FlashBang and it's free. 

I hope you like it. If you like it, I will send you pull request, editable files/original source and .png format files. If there's something you want to change, I'll do it.

What the color you like?
![logo](https://user-images.githubusercontent.com/38547278/39555518-09eb619a-4ea4-11e8-8430-4ae2827fa85a.png)

**Comment by zularizal** [comment]
Which one do you like? 1, 2 or 3?

And how do the featured graphics look like this?

![featured](https://user-images.githubusercontent.com/38547278/39565571-ab9a3da2-4ee2-11e8-98d1-2abf62d61478.png)

**Comment by imallett** [comment]
Ah, I preferred the original, with the lightning bolt upright and the sound waves coming out horizontally.

I realize I was perhaps unclear on what I meant. Here's a mockup:

![sketch](https://user-images.githubusercontent.com/8649790/39566878-4af48f9c-4e7a-11e8-8101-77fb5e0adf84.png)

The alignment of the edges was what I noticed in the original (left column): the edges of the sound waves didn't align with the edges of the lightning bolt (see red reference lines). In the center/right columns, I've hackishly messed with the image to make it line up. That's all I was suggesting. I like the center version here a lot.

I like the approach of the featured graphics very much.

**Comment by zularizal** [comment]
Do you mean like this? or do you prefer the original one?

![liek](https://user-images.githubusercontent.com/38547278/39573403-4341e294-4efd-11e8-869c-9422a2aa5df9.png)

**Comment by imallett** [comment]
Sorry for the delay. I mean like this:

![image1](https://user-images.githubusercontent.com/8649790/39667086-b59717e6-506b-11e8-8113-64517d053d64.png)

**Comment by zularizal** [comment]
Hi @imallett , I already uploaded logo, icons 512x512 and featured image for playstore to the drive. 
https://drive.google.com/open?id=1Ke0tyt3EEl56puYopEqeUg_QbCVK4Fe4

And also I've sent a pull request, please check #2

**Comment by imallett** [comment]
Thanks for your help! I've merged in your pull request, and will be making some commits to restructure, add in the source files into the repo also, and remove my old logo. Then I'll make a new release.
